In [ ]:
#참조사이트
#https://velog.io/@fiifa92/%ED%94%BC%EB%A7%88-%EC%9D%B8%EB%94%94%EC%96%B8-%EB%8B%B9%EB%87%A8%EB%B3%91-%EC%98%88%EC%B8%A1-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%84%B8%ED%8A%B8%EB%A1%9C-%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D-%ED%8F%89%EA%B0%80%ED%95%98%EA%B8%B0


In [ ]:
'''
Pregnancies: 임신 횟수
Glucose: 포도당 부하 검사 수치
BloodPressure: 혈압(mm Hg)
SkinThickness: 팔 삼두근 뒤쪽의 피하지방 측정값(mm)
Insulin: 혈청 인슐린(mu U/ml)
BMI: 체질량지수(체중(kg)/키(m))^2
DiabetesPedigreeFunction: 당뇨 내력 가중치 값
Age: 나이
Outcome: 클래스 결정 값(0 또는 1)
'''


'\nage: 나이\nsex: 성별\nbmi: Body mass index\nbp: Average blood pressure\n혈청에 대한 6가지 지표들\nS1, S2, S3, S4, S5, S6\n'

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [19]:
folder_path='/content/drive/MyDrive/Colab Notebooks/당뇨병예측_240902_고수클래스연계/data_folder'

In [20]:
!ls '/content/drive/MyDrive/Colab Notebooks/당뇨병예측_240902_고수클래스연계/data_folder'

diabetes_testset30_answer.csv  diabetes_testset30.csv  diabetes_train.csv


In [70]:
import pandas as pd
train = pd.read_csv(folder_path+'/'+'diabetes_train.csv')
test30 = pd.read_csv(folder_path+'/'+'diabetes_testset30.csv')

In [71]:
#잠깐!! 클릭전에 ... 결측치를 보완해주는 옵션 2
'''
zero_features = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
mean_zero_features = train[zero_features].mean()
print(mean_zero_features)
train[zero_features] = train[zero_features].replace(0, mean_zero_features)
test30[zero_features] = test30[zero_features].replace(0, mean_zero_features)
display(train.head())
display(test30.head())
'''


"\nzero_features = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']\nmean_zero_features = train[zero_features].mean()\nprint(mean_zero_features)\ntrain[zero_features] = train[zero_features].replace(0, mean_zero_features)\ntest30[zero_features] = test30[zero_features].replace(0, mean_zero_features)\ndisplay(train.head())\ndisplay(test30.head())\n"

In [72]:
#display(train.head())
display(test30.head())

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2       99             60             17      160  36.6   
1            1      102             74              0        0  39.5   
2           11      120             80             37      150  42.3   
3            3      102             44             20       94  30.8   
4            1      109             58             18      116  28.5   

   DiabetesPedigreeFunction  Age     Sex  
0                     0.453   21  Female  
1                     0.293   42    Male  
2                     0.785   48    Male  
3                     0.400   26    Male  
4                     0.219   22    Male

In [73]:
# 칼럼명 바꾸기
#df = data.rename(columns={'Age': 'age', 'BMI': 'bmi','BloodPressure': 'bp','Pregnancies': 's1', 'Glucose': 's2', 'SkinThickness': 's3', 'DiabetesPedigreeFunction': 's4', 'Outcome':'target'  })
#df=df[['age', 'bmi', 'bp', 's1', 's2', 's3', 's4', 'target']]

In [74]:
# Feature 셋과 Label 셋 분리
X = train.drop(columns=['Outcome'])
Y = train['Outcome']

In [75]:
display(X.head())
display(Y.head())

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age     Sex  
0                     0.627   50    Male  
1                     0.351   31  Female  
2                     0.672   32    Male  
3                     0.167   21  Female  
4                     2.288   33  Female

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [76]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 738 entries, 0 to 737
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               738 non-null    int64  
 1   Glucose                   738 non-null    int64  
 2   BloodPressure             738 non-null    int64  
 3   SkinThickness             738 non-null    int64  
 4   Insulin                   738 non-null    int64  
 5   BMI                       738 non-null    float64
 6   DiabetesPedigreeFunction  738 non-null    float64
 7   Age                       738 non-null    int64  
 8   Sex                       738 non-null    object 
 9   Outcome                   738 non-null    int64  
dtypes: float64(2), int64(7), object(1)
memory usage: 57.8+ KB


In [77]:
#0의 개수를 확인하고, 평균값으로 바꿔주기..
zero_features = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
total_count = train['Glucose'].count()
for feature in zero_features:
    zero_count = train[train[feature]==0][feature].count()
    print('{0} 0 건수는 {1}, 퍼센트는 {2:.2f} %'.format(feature, zero_count, 100*zero_count/total_count))

Glucose 0 건수는 5, 퍼센트는 0.68 %
BloodPressure 0 건수는 35, 퍼센트는 4.74 %
SkinThickness 0 건수는 218, 퍼센트는 29.54 %
Insulin 0 건수는 358, 퍼센트는 48.51 %
BMI 0 건수는 11, 퍼센트는 1.49 %


In [78]:
#mean_zero_features = train[zero_features].mean()
#train[zero_features] = train[zero_features].replace(0, mean_zero_features)

In [79]:
# 전처리 1번 : 레이블링(숫자 인코딩) train과 test30을 동시에 한다.
from sklearn.preprocessing import LabelEncoder
# 레이블 인코더 생성
cjk_encoder = LabelEncoder()
# 'Sex' 열에 레이블 인코딩 적용
X['Sex'] = cjk_encoder.fit_transform(X['Sex'])
test30['Sex'] = cjk_encoder.transform(test30['Sex'])
display(X.head())
display(test30.head())


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Sex  
0                     0.627   50    1  
1                     0.351   31    0  
2                     0.672   32    1  
3                     0.167   21    0  
4                     2.288   33    0

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2       99             60             17      160  36.6   
1            1      102             74              0        0  39.5   
2           11      120             80             37      150  42.3   
3            3      102             44             20       94  30.8   
4            1      109             58             18      116  28.5   

   DiabetesPedigreeFunction  Age  Sex  
0                     0.453   21    0  
1                     0.293   42    1  
2                     0.785   48    1  
3                     0.400   26    1  
4                     0.219   22    1

In [80]:
# 전처리 2번 : 스케일링(표준화) train과 test30을 동시에 한다.
from sklearn.preprocessing import StandardScaler
# 데이터 표준화 (Standardization)
scaler = StandardScaler()
X_train = scaler.fit_transform(X)
test30 = scaler.transform(test30)
display(X_train[0:3])
display(test30[0:3])

array([[ 0.65221293,  0.85382138,  0.1580658 ,  0.91334349, -0.69502552,
         0.21659885,  0.46584863,  1.44029538,  1.02747764],
       [-0.84446973, -1.11403522, -0.14878004,  0.53639457, -0.69502552,
        -0.66808621, -0.36537739, -0.18068719, -0.97325719],
       [ 1.250886  ,  1.94707505, -0.25106198, -1.28552522, -0.69502552,
        -1.08515202,  0.60137461, -0.09537232,  1.02747764]])

array([[-0.5451332 , -0.67673376, -0.45562587, -0.21750327,  0.68981828,
         0.59574959, -0.05818517, -1.03383591, -0.97325719],
       [-0.84446973, -0.5830263 ,  0.26034774, -1.28552522, -0.69502552,
         0.96226197, -0.54005533,  0.7577764 ,  1.02747764],
       [ 2.14889559, -0.02078155,  0.56719357,  1.03899314,  0.60326554,
         1.316136  ,  0.94169541,  1.26966563,  1.02747764]])

In [81]:
print(type(X_train))
print(type(Y))


<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [82]:
# X_train, Y 학습
# 학습용 데이터와 테스트용 데이터로 분리
X_train, X_test, y_train, y_test = train_test_split(X_train, Y, test_size=0.2, random_state=42)

In [83]:
from sklearn.linear_model import LogisticRegression
# 로지스틱 회귀 모델 초기화 및 학습
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [84]:
from sklearn.metrics import accuracy_score, classification_report
# 예측 및 평가
# 예측 수행
y_pred = model.predict(X_test)

# 모델 평가
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"모델 정확도: {accuracy}")
print("분류 보고서:\n", report)

모델 정확도: 0.7702702702702703
분류 보고서:
               precision    recall  f1-score   support

           0       0.78      0.88      0.82        91
           1       0.76      0.60      0.67        57

    accuracy                           0.77       148
   macro avg       0.77      0.74      0.75       148
weighted avg       0.77      0.77      0.76       148



In [ ]:
# 정확도는 77점 나옴..  만일 기준이 80점이면 다른 방법을 강구.. --> 이런 결측치를 보완하니 오히려 76점.. 원복

In [87]:
import pickle
filename = '01095962580_1.md5'
pickle.dump(model, open(filename, 'wb'))


In [88]:
!ls

01095962580_1.md5  01095962580_1.sav  drive  sample_data


In [90]:
# test로 예측해서 CSV로 저장하기
pred = model.predict(test30)
print(pred)
#예측결과 77점..

[0 0 1 0 0 1 1 0 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0]


In [91]:
len(pred)

30

In [92]:
#결과로 저장하기
test30_r = pd.read_csv(folder_path+'/'+'diabetes_testset30.csv')

In [93]:
test30_r['Outcome'] = pred

In [94]:
test30_r.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2       99             60             17      160  36.6   
1            1      102             74              0        0  39.5   
2           11      120             80             37      150  42.3   
3            3      102             44             20       94  30.8   
4            1      109             58             18      116  28.5   

   DiabetesPedigreeFunction  Age     Sex  Outcome  
0                     0.453   21  Female        0  
1                     0.293   42    Male        0  
2                     0.785   48    Male        1  
3                     0.400   26    Male        0  
4                     0.219   22    Male        0

In [95]:
test30_r.to_csv('01095962580_1.csv', index=False)

In [ ]:
# 모델 불러서 사용하기..
import joblib

# 모델 저장
joblib.dump(model, 'diabetes_model.pkl')


In [ ]:
# 저장된 모델 불러오기
loaded_model = joblib.load('diabetes_model.pkl')

# 불러온 모델로 예측 수행
y_pred_loaded = loaded_model.predict(X_test)

# 모델 평가
accuracy_loaded = accuracy_score(y_test, y_pred_loaded)
print(f"불러온 모델의 정확도: {accuracy_loaded}")


In [ ]:
#1. scaler와 모델 함께 저장하기
import joblib

# 모델과 scaler를 딕셔너리에 담기
model_pipeline = {
    'model': model,
    'scaler': scaler
}

# 딕셔너리 저장
joblib.dump(model_pipeline, 'diabetes_model_pipeline.pkl')

In [ ]:
# 모델과 scaler 불러오기
loaded_pipeline = joblib.load('diabetes_model_pipeline.pkl')

# 모델과 scaler 추출
loaded_model = loaded_pipeline['model']
loaded_scaler = loaded_pipeline['scaler']

# 새로운 데이터에 적용 (예를 들어 X_new 데이터가 있다고 가정)
# X_new = ...

# 새로운 데이터에 스케일러 적용
X_new_scaled = loaded_scaler.transform(X_new)

# 불러온 모델로 예측
y_new_pred = loaded_model.predict(X_new_scaled)