In [1]:
import pandas as pd

In [2]:
from tensorflow.keras.datasets.boston_housing import load_data

# 데이터를 다운받습니다.
(x_train_org, y_train_org), (x_test_org, y_test_org) = load_data(path='boston_housing.npz',
                                                 test_split=0.2,
                                                 seed=777)

print(x_train_org.shape, y_train_org.shape)
print(x_test_org.shape, y_test_org.shape)




57026/57026 [==============================] - 0s 1us/step
(404, 13) (404,)
(102, 13) (102,)


In [3]:
df=pd.DataFrame(x_train_org)

In [4]:
y_train_org[:10]

array([22.5,  8.3, 17.2, 25. , 28.5, 23. , 18.9, 50. , 15.6, 38.7])

In [5]:
df.head()

0     1      2    3      4      5     6       7     8      9     10  \
0   0.25199   0.0  10.59  0.0  0.489  5.783  72.7  4.3549   4.0  277.0  18.6   
1  15.86030   0.0  18.10  0.0  0.679  5.896  95.4  1.9096  24.0  666.0  20.2   
2   7.40389   0.0  18.10  0.0  0.597  5.617  97.9  1.4547  24.0  666.0  20.2   
3   0.12650  25.0   5.13  0.0  0.453  6.762  43.4  7.9809   8.0  284.0  19.7   
4   0.03502  80.0   4.95  0.0  0.411  6.861  27.9  5.1167   4.0  245.0  19.2   

       11     12  
0  389.43  18.06  
1    7.68  24.39  
2  314.64  26.40  
3  395.58   9.50  
4  396.90   3.33

In [45]:
import numpy as np

# 데이터 표준화
x_mean = np.mean(x_train_org, axis = 0)
x_std = np.std(x_train_org, axis = 0)
print(type(x_mean), type(x_std))
print(x_mean.shape, x_std.shape)
x_train = (x_train_org - x_mean) / x_std
x_test = (x_test_org - x_mean) / x_std

y_mean = np.mean(y_train_org, axis = 0)
y_std = np.std(y_train_org, axis = 0)
print(type(y_mean), type(y_std))
print(y_mean.shape, y_std.shape)
y_train = (y_train_org - y_mean) / y_std
y_test = (y_test_org - y_mean) / y_std

print(x_train[0])
print(y_train[0])

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(13,) (13,)
<class 'numpy.float64'> <class 'numpy.float64'>
() ()
[-0.40102395 -0.48033655 -0.12089418 -0.28828791 -0.58254176 -0.68137272
  0.11117586  0.26484408 -0.65187119 -0.80249043  0.0756568   0.37366783
  0.69211835]
0.03134230990794722


In [16]:
# 검증 데이터셋을 만듭니다.
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train,
                                                  test_size = 0.2,
                                                  random_state = 42)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
# 입력 데이터의 형태를 꼭 명시해야 합니다.
# 13차원의 데이터를 입력으로 받고, 64개의 출력을 가지는 첫 번째 Dense 층
model.add(Dense(64, activation = 'relu', input_shape = (13, )))
model.add(Dense(32, activation = 'relu')) # 32개의 출력을 가지는 Dense 층
model.add(Dense(1)) # 하나의 값을 출력합니다.

model.compile(optimizer = 'adam', loss = 'mse', metrics = ['mae'])
history = model.fit(x_train, y_train,
                    epochs = 300,
                    validation_data = (x_val, y_val))
print(model.evaluate(x_test, y_test))
# 결과값 : [9.451594831896763, 2.2150924] 평균, 표준편차

In [ ]:
#x_train = (x_train - mean) / std
#x_test = (x_test - mean) / std

In [ ]:
#시험 결과 표기

In [18]:
x_test_org[0]

array([1.6902e-01, 0.0000e+00, 2.5650e+01, 0.0000e+00, 5.8100e-01,
       5.9860e+00, 8.8400e+01, 1.9929e+00, 2.0000e+00, 1.8800e+02,
       1.9100e+01, 3.8502e+02, 1.4810e+01])

In [19]:
df.iloc[:1]

0    1      2    3      4      5     6       7    8      9     10  \
0  0.25199  0.0  10.59  0.0  0.489  5.783  72.7  4.3549  4.0  277.0  18.6   

       11     12  
0  389.43  18.06

In [24]:
test_list=df.iloc[:3].values
test_list

array([[2.51990e-01, 0.00000e+00, 1.05900e+01, 0.00000e+00, 4.89000e-01,
        5.78300e+00, 7.27000e+01, 4.35490e+00, 4.00000e+00, 2.77000e+02,
        1.86000e+01, 3.89430e+02, 1.80600e+01],
       [1.58603e+01, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.79000e-01,
        5.89600e+00, 9.54000e+01, 1.90960e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 7.68000e+00, 2.43900e+01],
       [7.40389e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 5.97000e-01,
        5.61700e+00, 9.79000e+01, 1.45470e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.14640e+02, 2.64000e+01]])

In [29]:
a=test_list[0]
print(a.shape)
b=a.reshape(1,13) # 항상 배치형으로 앞에 들어가줘얗 ㅏㅁ
print(b.shape)

(13,)
(1, 13)


In [30]:
for i,item in enumerate(test_list):
  st_target=(item-mean)/std
  result=model.predict(st_target.reshape(1,13))
  print(result)
  if(i==10):
    break

1/1 [==============================] - 0s 96ms/step
[[-5.5794253]]
1/1 [==============================] - 0s 55ms/step
[[0.7157624]]
1/1 [==============================] - 0s 27ms/step
[[3.6198258]]


In [31]:
list(test_list)

[array([2.5199e-01, 0.0000e+00, 1.0590e+01, 0.0000e+00, 4.8900e-01,
        5.7830e+00, 7.2700e+01, 4.3549e+00, 4.0000e+00, 2.7700e+02,
        1.8600e+01, 3.8943e+02, 1.8060e+01]),
 array([ 15.8603,   0.    ,  18.1   ,   0.    ,   0.679 ,   5.896 ,
         95.4   ,   1.9096,  24.    , 666.    ,  20.2   ,   7.68  ,
         24.39  ]),
 array([7.40389e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 5.97000e-01,
        5.61700e+00, 9.79000e+01, 1.45470e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.14640e+02, 2.64000e+01])]

In [32]:
x_test[0]

array([-0.40993096, -0.48033655,  2.05226513, -0.28828791,  0.19360146,
       -0.39363321,  0.67181047, -0.83696465, -0.87754039, -1.3232612 ,
        0.30547144,  0.32733271,  0.24563206])

In [33]:
x_test[0].shape

(13,)

In [34]:
x_test[0].reshape(1, 13).shape

(1, 13)

In [35]:
x_test[0].reshape(1, 13)

array([[-0.40993096, -0.48033655,  2.05226513, -0.28828791,  0.19360146,
        -0.39363321,  0.67181047, -0.83696465, -0.87754039, -1.3232612 ,
         0.30547144,  0.32733271,  0.24563206]])

In [ ]:
a=model.predict(x_test[0].reshape(1, 13))

1/1 [==============================] - 0s 65ms/step


In [ ]:
a

array([[21.88225]], dtype=float32)

In [37]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
cjk = ss.fit(x_train_org)  #x_train_org에 맞춘것을 기준으로 하기 때문에... fit은 SS만 사용
mydf_n = ss.transform(x_train_org)

In [41]:
cjk

StandardScaler()

In [38]:
mydf_n

array([[-0.40102395, -0.48033655, -0.12089418, ...,  0.0756568 ,
         0.37366783,  0.69211835],
       [ 1.27456268, -0.48033655,  0.96279947, ...,  0.81106366,
        -3.63731409,  1.56173624],
       [ 0.36674834, -0.48033655,  0.96279947, ...,  0.81106366,
        -0.4121379 ,  1.83787084],
       ...,
       [-0.32196549, -0.48033655, -0.4744294 , ...,  1.17876709,
         0.42735772,  0.94215066],
       [-0.41947243, -0.48033655, -0.78900359, ...,  0.35143437,
         0.45215384, -0.58414552],
       [-0.3884412 , -0.48033655, -0.22046124, ..., -0.01626906,
         0.43944058, -0.51408152]])

In [39]:
shd = ss.transform(x_test_org[0].reshape(1,13))

In [40]:
shd

array([[-0.40993096, -0.48033655,  2.05226513, -0.28828791,  0.19360146,
        -0.39363321,  0.67181047, -0.83696465, -0.87754039, -1.3232612 ,
         0.30547144,  0.32733271,  0.24563206]])

In [42]:
result=model.predict(shd)

1/1 [==============================] - 0s 35ms/step


In [43]:
print(result)

[[-0.22306746]]


In [46]:
#y_train = (y_train_org - mean) / std
print((result*y_std)+y_mean)

[[20.157282]]
